//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace glazki_save.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clients
    {
        public int id { get; set; }
        public string FIO { get; set; }
        public Nullable<int> Code_Clienta { get; set; }
        public string Passport_Data { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Adress { get; set; }
        public string e_mail { get; set; }
        public string Password { get; set; }
        public Nullable<int> id_zakaza { get; set; }
    
        public virtual zakazy zakazy { get; set; }
    }
}
