//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace glazki_save.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class role
    {
        public int RoleID { get; set; }
        public string Title { get; set; }
    
        public virtual user user { get; set; }
    }
}
