//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace glazki_save.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class uslugi
    {
        public int ID { get; set; }
        public string title { get; set; }
        public string code { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> id_zakazy { get; set; }
    
        public virtual zakazy zakazy { get; set; }
    }
}
