//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF___Свияжские_холмы
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Pasport { get; set; }
        public Nullable<System.DateTime> DateBirth { get; set; }
        public string Address { get; set; }
        public string Password { get; set; }
    }
}
