//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF___Свияжские_холмы
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceByTour
    {
        public Nullable<int> ID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public string IsControl { get; set; }
    }
}
